2.1.3 release
10up/brightcove-video-connect pull request #201
Opened 2021-06-02 21:16 UTC by Rahmon

### Description of the Change

### Alternate Designs

### Benefits

### Possible Drawbacks

### Verification Process

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

### Changelog Entry

2021-06-02 21:26 UTC, jeffpaul commented
will want to bump https://github.com/10up/brightcove-video-connect/blob/7312968e658fb01decd05d325f8a56fa4302def2/package.json#L6 as well

2021-06-02 21:27 UTC, jeffpaul commented
also https://github.com/10up/brightcove-video-connect/blob/7312968e658fb01decd05d325f8a56fa4302def2/brightcove-video-connect.php#L6

2021-06-03 14:12 UTC, oscarssanchez requested changes

2021-06-03 14:12 UTC, oscarssanchez commented on CHANGELOG.md
>  ## [2.1.2] TBD
Let's add the release date here @Rahmon you can grab this info from: https://github.com/10up/brightcove-video-connect/releases/tag/2.1.2 

I usually leave the TBD to the most recent one, as sometimes the release date is not the same the releas PR is submitted

2021-06-03 14:12 UTC, oscarssanchez commented on readme.txt
> -Stable tag: 2.1.2
Let's also add the changes to the Changelog like this @Rahmon : https://github.com/10up/brightcove-video-connect/pull/196/files#diff-9e6e4772050998a5c0dc3c61acf3dab0a7e594566171fa5746d6b62f9598efb6R25

2021-06-03 16:59 UTC, Rahmon commented on readme.txt
> -Stable tag: 2.1.2
@oscarssanchez Updated.

2021-06-03 17:03 UTC, Rahmon commented on CHANGELOG.md
>  ## [2.1.2] TBD
Updated @oscarssanchez

2021-06-03 17:06 UTC, oscarssanchez approved these changes

2021-06-03 17:09 UTC, merged