Use wp.blockEditor.BlockControls if available
10up/brightcove-video-connect pull request #342
Opened 2023-09-11 17:22 UTC by felipeelia

### Description of the Change

Closes #334

### How to test the Change

### Changelog Entry

> Changed - Use wp.blockEditor.BlockControls if available

### Credits

Props @felipeelia and @oscarssanchez 

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2023-09-11 18:03 UTC, felipeelia commented on assets/js/src/block.js
> +						el(Dashicon, { icon: 'edit' }),
Added it as the component content because the `icon` attribute was not available in WP 5.2.

2023-09-12 07:10 UTC, JakePT requested changes

2023-09-12 07:10 UTC, JakePT commented on assets/js/src/block.js
> +	const BlockControls = blockEditor.BlockControls || editor.BlockControls;
@felipeelia If `blockEditor` doesn't exist then I believe this will throw an error, so it would never be able to fall back to `editor.blockControls`. According to the error message `editor.blockControls` was deprecated in 5.3, so it's been around at least that long. It looks like the plugin needs to support 4.2+ so you would need to check whether it exists in 4.2. If it does, the fallback to `editor` isn't needed, otherwise the error will need to be corrected.

One option is to just use [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining):

```
const { blockEditor, editor } = wp;
const BlockControls = blockEditor?.BlockControls || editor.BlockControls;
```

But unless there is a build process with Babel this won't work on some older browsers (versions from early 2020).

For a bit better support (early 2018 versions) you could define some defaults when [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment):

```
const { blockEditor = {}, editor = {} } = wp;
const BlockControls = blockEditor.BlockControls || editor.BlockControls;
```

This way, since `blockEditor` will at least be an empty object, `blockEditor.BlockControls` won't throw an error if it doesn't exits.

2023-09-12 16:55 UTC, felipeelia commented on assets/js/src/block.js
> +	const BlockControls = blockEditor.BlockControls || editor.BlockControls;
@JakePT good point, thanks. The code already relies on the fact that wp.blockEditor exists, when it calls `InspectorControls = wp.blockEditor.InspectorControls` down a couple of lines. In fact, it seems the plugin is already incompatible with WP 5.1 and older.

2023-09-12 17:05 UTC, JakePT approved these changes

2023-10-10 20:07 UTC, merged