Relase 2.8.6
10up/brightcove-video-connect pull request #391
Opened 2024-05-07 16:23 UTC by oscarssanchezz

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2024-05-07 18:44 UTC, felipeelia requested changes

2024-05-07 18:44 UTC, felipeelia commented on CHANGELOG.md
> +## [2.8.6] - 2023-05-07
```suggestion
## [2.8.6] - 2024-05-07
```

2024-05-07 18:44 UTC, felipeelia commented on package-lock.json
> +  "version": "2.8.6",
this also needs to be changed in line 9

2024-05-07 18:44 UTC, felipeelia commented on readme.txt
> +- Typo when saving the language_detection attribute. Props [@claimableperc](https://github.com/claimableperc).
Can we make this list to start with `*` to line up with the previous ones?

2024-05-08 14:58 UTC, oscarssanchezz commented on CHANGELOG.md
> +## [2.8.6] - 2023-05-07
Fixed here: https://github.com/10up/brightcove-video-connect/pull/391/commits/dfba57ce996ef65a87983b7a4c40e977ae96c804#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edL16

2024-05-08 14:58 UTC, oscarssanchezz commented on package-lock.json
> +  "version": "2.8.6",
Fixed here https://github.com/10up/brightcove-video-connect/pull/391/commits/dfba57ce996ef65a87983b7a4c40e977ae96c804#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519R9

2024-05-08 14:59 UTC, oscarssanchezz commented on readme.txt
> +- Typo when saving the language_detection attribute. Props [@claimableperc](https://github.com/claimableperc).
Fixed here https://github.com/10up/brightcove-video-connect/pull/391/commits/dfba57ce996ef65a87983b7a4c40e977ae96c804#diff-9e6e4772050998a5c0dc3c61acf3dab0a7e594566171fa5746d6b62f9598efb6R46

2024-05-08 15:21 UTC, felipeelia commented on CHANGELOG.md
> +- Bugfix: combined queries with q search parameter. Props [@oscarssanchezz](https://github.com/oscarssanchezz/oscarssanchezz) via [#392](https://github.com/10up/brightcove-video-connect/pull/392).
```suggestion
-Combined queries with q search parameter. Props [@oscarssanchezz](https://github.com/oscarssanchezz/oscarssanchezz) via [#392](https://github.com/10up/brightcove-video-connect/pull/392).
```
(as it is already in the "Fixed" section, we don't need the "Bugfix" prefix ;) )

2024-05-08 15:56 UTC, felipeelia approved these changes

2024-05-08 15:57 UTC, merged